### ISSUE TITLE
Creating New Cabinet Doors  with G - section handle

### ISSUE THREAD

**Issue by akshaynikhare** [CreativeDesigner3D/Library_Home_Builder#35]
hey Andrew,

i want to add Door Style to the library can you guide how can i do that  
i started with by creating a copy of "Slab.bend" and created a new file 
i placed the handle which i required as below
![image](https://user-images.githubusercontent.com/9725336/102260190-1e0ec380-3f36-11eb-8fd8-10df224441ad.png)

but when i applied it did not scaled properly.
do i need to write some code apart from the *.blend file

**Comment by CreativeDesigner3D** [comment]
There is some setup required to make the assemblies change size correctly. I will have information about this soon.
