### ISSUE TITLE
"Create thumbnail for selected item' does not genrate a image

### ISSUE THREAD

**Issue by akshaynikhare** [CreativeDesigner3D/Library_Home_Builder#36]
when clicked it dose something , but there is no image generated  
![image](https://user-images.githubusercontent.com/9725336/102260602-ae4d0880-3f36-11eb-8d9d-ba12aba3deb7.png)

**Comment by CreativeDesigner3D** [comment]
it is most likely creating the thumbnails and overwriting the thumbnails that already exists. This is mainly used to create create thumbnails for assets that don't have them. I will have more detailed documentation about how this interface works soon.
