### ISSUE TITLE
Customize the default material pointers

### ISSUE THREAD

**Issue by aqp696** [CreativeDesigner3D/Library_Home_Builder#38]
Relates to #13 
# Summary
Possibility to customize the default material pointers in the home builder library. This way the user can define other predefined material for the cabinets (for example) without to changing them every time in a blender project.
# Affected version
Blender v2.91.2
Library_Home_Builder v0.3.1
# Steps to reproduce
* Open a new blender project
* Edit the preferences of the Home builder library and select the materials tab
![image](https://user-images.githubusercontent.com/1755312/108885155-bcd73080-7607-11eb-8296-15d490747890.png)
As you can see the options are the same defined in the file [home_builders_pointers.py](https://github.com/CreativeDesigner3D/Library_Home_Builder/blob/cb9ef2ecc759f9a9497c81f800cb78df0d135faf/home_builder_pointers.py)
```python
def get_default_material_pointers():
    pointers = []
    #CABINETS
    pointers.append(("Cabinet Unfinished Surfaces","_Sample","Particle Board"))
    pointers.append(("Cabinet Unfinished Edges","_Sample","Particle Board"))
    pointers.append(("Cabinet Exposed Surfaces","_Sample","Dark Wood"))
    pointers.append(("Cabinet Exposed Edges","_Sample","Dark Wood"))
    pointers.append(("Cabinet Interior Surfaces","_Sample","Dark Wood"))
    pointers.append(("Cabinet Interior Edges","_Sample","Dark Wood"))
    pointers.append(("Cabinet Door Surfaces","_Sample","Dark Wood"))
    pointers.append(("Cabinet Door Edges","_Sample","Dark Wood"))
    pointers.append(("Cabinet Pull Finish","_Sample","Polished Chrome"))
    pointers.append(("Countertop Surface","_Sample","Midnight Granite"))
```
# Feature proposal
Add a new menu option in the materials section to set the selected materials as the new defaults
![image](https://user-images.githubusercontent.com/1755312/108885732-6fa78e80-7608-11eb-924b-a3312b819084.png)

# Possible workaround
In the meantime a possible workaround is to select `File -> Defaults -> Save Startup File`

**Comment by CreativeDesigner3D** [comment]
This is a great proposal. I will put some thought into this. I have been wanting to add more customization to the material pointers interface. I'll keep this issue updated with my progress.

**Comment by CreativeDesigner3D** [comment]
I have implemented several more options for materials including the ability to create material groups and add material pointers. The ability to save defaults is currently done by saving the startup file.
