### ISSUE TITLE
Create Option for Door(s) & Drawer(s) in the Same Base Cabinet

### ISSUE THREAD

**Issue by arch267** [CreativeDesigner3D/Library_Home_Builder#61]
Currently base cabinets are either all-drawers or all-doors. It would be ideal to have the flexibility to combine door(s) + drawer(s) in the same unit. Ideally we would want at least the following combination:
- 1 variable height drawer on top with 1 or 2 doors below, depending on cabinet width.

**Comment by CreativeDesigner3D** [comment]
I have added three new cabinets to the library.

![image](https://user-images.githubusercontent.com/34818078/117546054-51cdb100-afdd-11eb-8f9b-1c5c2e310aed.png)
![image](https://user-images.githubusercontent.com/34818078/117546044-47abb280-afdd-11eb-91db-101293dcf737.png)
![image](https://user-images.githubusercontent.com/34818078/117546035-3ebae100-afdd-11eb-953a-a35c93035a96.png)

These are all essentially the same cabinet. In the exterior prompts you have the ability to change the doors swing, and select between 1 or 2 Drawers.
